# Generated by Django 3.0.7 on 2020-11-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201111_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='lor',
            field=models.FileField(default='lor.txt', upload_to='lor_docs'),
        ),
    ]
