# Generated by Django 3.0.7 on 2020-11-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201023_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
